name: Robot Manual
on: push

jobs:
  make_instructions:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: x64
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt update

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - name: Install requirements
      run: pip install -r docs/requirements.txt

    - run: cd docs && make latexpdf

    - run: mv docs/_build/latex/*.pdf docs/_build/latex/Unnamed_Toaster_Robot_Manual.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: Tidal_Force_Robot_Manual
        path: docs/_build/latex/FRC1721_Robot_Manual.pdf
    
    - name: Discord notification
      if: ${{ failure() }}
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Docs failed <@&614313406345904148>!'
